# Generated by Django 5.0.6 on 2024-06-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='donor_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
