# Generated by Django 5.0.6 on 2024-06-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blooddonor_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='lat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='long',
            field=models.CharField(max_length=10),
        ),
    ]
