# Generated by Django 5.0.6 on 2024-06-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blooddonor_lat_alter_blooddonor_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonor',
            old_name='long',
            new_name='lgs',
        ),
    ]
