# Generated by Django 5.0.6 on 2024-06-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_requests_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='sent_time',
            field=models.DateTimeField(null=True),
        ),
    ]
